# Generated by Django 4.1.6 on 2023-02-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addrecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=120)),
                ('recharge', models.CharField(max_length=120)),
                ('operator', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
