# Generated by Django 4.1.6 on 2023-02-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexy', '0002_addrecharge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addrecharge',
            old_name='recharge',
            new_name='amount',
        ),
    ]
