# Generated by Django 4.1.6 on 2023-02-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexy', '0003_rename_recharge_addrecharge_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addrecharge',
            old_name='mobile',
            new_name='phone',
        ),
    ]
